services:
  furia-bot:
    build: .
    container_name: furia_telegram_bot

    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}

    volumes:
      - furia_bot_persistence:/app/furia_bot_data

    restart: unless-stopped

volumes:
  furia_bot_persistence:
